# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AxiomTelecomAssignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher', '~> 5.0'


  # Pods for AxiomTelecomAssignment

  target 'AxiomTelecomAssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AxiomTelecomAssignmentUITests' do
    # Pods for testing
  end

end
